### PR TITLE
Change DB::open_cf signature to the more generic one

### LINKED ISSUE #175: DB::open_cf signature
It is inconvenient to use `open_cf` function with the result of `list_cf`. It requires transforming `Vec<String>` to `&[&str]`. The signature can be made more generic the following way:
```rust
pub fn open_cf<P: AsRef<Path>, N: AsRef<str>>(opts: &Options, path: P, cfs: &[N]) -> Result<DB, Error>
```

### PR DESCRIPTION
**Pull request by DarkEld3r**
Closes #175.

### CODE REVIEW

**Comment by DarkEld3r** [comment]
This is a little bit controversial, but I suppose that `open_cf` function is mostly used in combination with `list_cf` and it will be a little more optimal to pass `IntoIterator` in that case.

**Comment by iSynaptic** [comment]
> 
> 
> This is a little bit controversial, but I suppose that `open_cf` function is mostly used in combination with `list_cf` and it will be a little more optimal to pass `IntoIterator` in that case.

@DarkEld3r Curious: What makes this change controversial?

**Comment by iSynaptic** [comment]
Closing due to branch conflicts and inactivity.

**Comment by DarkEld3r** [comment]
@iSynaptic Sorry, I somehow missed your question. I suppose it isn't actual anymore and I don't remember all details already, but I wasn't sure if such signature change would be OK.

**Pull request closed without merging**
