### PR TITLE
Make MergeFn into a trait, so stateful closures can be passed as a merge operator.

### PR DESCRIPTION
**Pull request by mrobakowski**
In one of my projects I needed to pass stateful closures as merge operators, so here's a PR that implements that. The changes are quite small but unfortunately, this is a breaking change, since now `full_merge_fn` and `partial_merge_fn` can be of different types, and I split `set_merge_operator` into `set_merge_operator` and `set_merge_operator_associative`.

### CODE REVIEW

**Comment by jparr721** [comment]
Any movement on this recently? I have a use case for this and would love to see it added. Happy to pick up where he lft off if needed.

**Comment by mrobakowski** [comment]
I'm happy to work on it further, I just want feedback. I honestly don't know why the tests don't pass because I mostly copied another test and slightly changed it. It all passes locally.

**Comment by BoOTheFurious** [comment]
Hello,

Any movement on this recently? I have a use case for this and would like to see it added.

Regards

**Comment by mrobakowski** [comment]
Closing in favor of https://github.com/rust-rocksdb/rust-rocksdb/pull/481. Thanks @BoOTheFurious!

**Pull request closed without merging**
