### PR TITLE
Bump uuid and bindgen dependencies

### LINKED ISSUE #384: Old version of bindgen brings in old dependencies
The newest version of `bindgen` is `0.52.0`. It'd be good to update to it so that various transitive dependencies also get updated.

### PR DESCRIPTION
**Pull request by jonhoo**
Fixes #384.

### CODE REVIEW

**Comment by jonhoo** [comment]
Also note that irrespective of this PR, I think a crates.io release should be made to `librocksdb-sys`, since the latest version on crates.io is 6.2.4.

**Comment by jonhoo** [comment]
If the version needs to stay `6.4.6`, I would recommend merging this and _then_ publishing 6.4.6. It's not entirely clear whether this change is backwards-compatible (I don't know if the generated code is "the same"), but if the versioning of the crate is tied to the versioning of the rocksdb lib, we may not have much of a choice.

**Comment by jonhoo** [comment]
Haha, no, sadly not — this is just a part of my everyday workday :sweat_smile:

**Comment by jonhoo** [comment]
Interesting, these build failures look mostly unrelated to this change, but I'll dig a little: https://travis-ci.org/rust-rocksdb/rust-rocksdb/jobs/651573400?utm_medium=notification&utm_source=github_status

**Comment by jonhoo** [comment]
Yeah, the same build failure occurs on `master` on Windows:
https://travis-ci.org/rust-rocksdb/rust-rocksdb/branches

**Comment by aleksuss** [comment]
@jonhoo never mind. It's known issue on windows host. Everything is ok.

**Comment by jonhoo** [comment]
Seems to pass on the other two platforms at least :tada:

**Comment by jonhoo** [comment]
@aleksuss Nice! What's the next steps for getting out a release of `librocksdb-sys`?

**Comment by aleksuss** [comment]
@jonhoo Usually, I publish a new `librocksdb-sys` release together with the main crate. To be honest, I haven't decided when to publish a new release yet.

**Comment by jonhoo** [comment]
Is there a particular reason you don't want to release a new minor release of `librocksdb-sys` without also doing a new release of `rocksdb`? Presumably the latter has more breaking changes and such than the former, and the releases are mostly independent?

**Comment by jonhoo** [comment]
Alternatively, would you consider doing a patch release of `rocksdb` (so `0.13.1`) that includes the bump to `librocksdb-sys`?

**Comment by aleksuss** [comment]
Yeah. I will think about it. I suppose it's a good idea.

**Comment by jonhoo** [comment]
I expect it will cut compile times for certain crates pretty drastically, as they no longer need to build multiple versions of `syn`, `quote`, and `bindgen`.

**Comment by jonhoo** [comment]
@aleksuss have you had a chance to think some more about whether to release new versions of `librocksdb-sys`?

**Comment by aleksuss** [comment]
Done https://crates.io/crates/librocksdb-sys I hope it would be enough for you ? 🙂

**Comment by jonhoo** [comment]
Beautiful, thank you!

**Pull request merged**
