### PR TITLE
Support building RocksDB with jemalloc

### PR DESCRIPTION
**Pull request by akrylysov**
RocksDB includes some optimizations when it's compiled with jemalloc. This PR allows enabling jemalloc using new `jemalloc` feature.

### CODE REVIEW

**Review by aleksuss — COMMENTED** [review]
Overall looks good. But I'd recommend to add a check of this feature to Github Actions CI.

**Comment by aleksuss** [comment]
> Warning: "jemalloc support for `x86_64-pc-windows-msvc` is untested"

As I can see `jemalloc` [doesn't support](https://crates.io/crates/jemallocator) `x86_64-pc-windows-msvc` target.

**Comment by akrylysov** [comment]
Thanks for taking a look. I converted the PR to a draft for now until I can figure out the best way to handle Windows.

**Comment by akrylysov** [comment]
I tried using the `x86_64-pc-windows-gnu` target on Windows (the default target is `x86_64-pc-windows-msvc`), but unfortunately jemalloc fails to compile as well. I disabled jemalloc tests on Windows.

Non-glibc allocator is a must-have for RocksDB on Linux in production. Here is more details on switching to jemalloc http://smalldatum.blogspot.com/2018/04/myrocks-malloc-and-fragmentation-strong.html or other alternative allocator https://blog.cloudflare.com/the-effect-of-switching-to-tcmalloc-on-rocksdb-memory-use/.

**Comment by aleksuss** [comment]
PR #547 resolve clippy warings.

**Review by aleksuss — APPROVED** [review]

**Comment by akrylysov** [comment]
I'm not sure why the CI fails now, GitHub Actions doesn't show any error output 😕

**Comment by aleksuss** [comment]
Probably, there was something wrong with CI. I restarted jobs and it's ok now.

**Pull request merged**
