### PR TITLE
librocksdb-sys: update rocksdb to 6.11.4

### PR DESCRIPTION
**Pull request by ordian**
Any chance to get this published soon? :)

### CODE REVIEW

**Comment by ordian** [comment]
Hey, there has been a few PRs merged for 6.8.1 (#428), 6.10.2 (#444), 6.11.4 (this), but non of them released to crates.io.
The latest released version of librocksdb-sys is 6.7.4. Would be nice to know what's blocking the release?

**Comment by DarkEld3r** [comment]
I think this makes sense.
@aleksuss Are we waiting for something? I guess we can release a new version.

**Comment by aleksuss** [comment]
Yes, we can. I'll do it soon.

**Comment by ordian** [comment]
@aleksuss any updates? :)

**Comment by aleksuss** [comment]
@ordian yeap 😄 #458

**Comment by ordian** [comment]
cool, but I assumed that `librocksdb-sys` and `rocksdb` versions can be bumped independently, is that not the case? I was requesting for `librocksdb-sys` to be published to be specific.

**Comment by aleksuss** [comment]
I got it. Yes, I don't see any reason don't do that right now.

**Pull request merged**
