### PR TITLE
Applied clippy lints

### PR DESCRIPTION
**Pull request by aleksuss**

### CODE REVIEW

**Comment by iSynaptic** [comment]
@aleksuss Is there an opportunity to make Clippy part of the CI build?

**Comment by aleksuss** [comment]
@iSynaptic I don't think so because format of `bindgen.rs` file is unpredictable.

**Comment by iSynaptic** [comment]
@aleksuss Could `bindgen.rs` be ignored by Clippy?

**Comment by aleksuss** [comment]
@iSynaptic I don't know right now but I will think about this. Actually It's a really good idea to add clippy's check in CI. 👍🏻

**Pull request merged**
