### PR TITLE
Made the DBIterator new functions public - To support passing ReadOptions to iterator

### PR DESCRIPTION
**Pull request by elichai**
Hi,
I want to use `DBIterator` with `set_iterate_upper_bound`, but no iterator function opens the possibility to give my own ReadOptions.

I think just making `DBIterator::new()` public is the simplest solution, although maybe it's better to add functions to DB that will support transforming it into an iterator and receiving Readoptions.

Thanks.

### CODE REVIEW

**Comment by elichai** [comment]
@iSynaptic Can I get some feedback on this? Thanks!

**Comment by iSynaptic** [comment]
> @iSynaptic Can I get some feedback on this? Thanks!

Sure. As you noted, the historical approach has been to add functions to the `DB` impl to expose this kind of functionality. To keep things consistent with the current Rust library, it might be better to continue with that.

However, I wonder if this is the right long term approach.  The core library exposes a [`NewIterator`](https://github.com/facebook/rocksdb/wiki/Basic-Operations#iteration) function on the `DB` that takes in a `ReadOptions`. It might be worth shifting to that approach to keep things consistent with the core library.

**Comment by elichai** [comment]
Whatever you decide :), 
I can implement it myself if you'd like (at least the first one, changing the whole approach might take too much time for me to invest)

Thanks!

**Comment by iSynaptic** [comment]
@vitvakatu @aleksuss What are your thoughts?

**Comment by vitvakatu** [comment]
Well, I think that we decided to follow parent library's design decisions as long as it's possible, didn't we? So I think we might better split responsibilities a bit and use some kind of `NewIterator`.
Although if it's a blocker @elichai, we might consider merging this PR and change API later.

**Comment by elichai** [comment]
Thanks for the consideration.
Right now I'm just pointing to my github for it and it's fine cause my code is still not on crates.io

But if you'll make a design on how  the new iterator should be I can try and contribute however I can.

**Comment by iSynaptic** [comment]
I'm going to make a PR to move iterator construction to the `DB` object and make sure it exposes a `&ReadOptions` argument. You can watch my progress on [this branch](https://github.com/iSynaptic/rust-rocksdb/tree/ergonomics-and-safety), along with some other ergonomic and safety updates.

**Pull request closed without merging**
