### PR TITLE
Added a possibility to enable mmap files for reads and writes

### PR DESCRIPTION
**Pull request by aleksuss**

### CODE REVIEW

**Comment by pakipaki2000** [comment]
Hi,

When will this be available in the crates.io?

Thank you

**Comment by HandleMaser** [comment]
Badly waiting for it too :(

**Comment by pakipaki2000** [comment]
Please guy :(

**Comment by iSynaptic** [comment]
See #287

**Comment by iSynaptic** [comment]
Just released 0.12.1.

**Pull request merged**
