### PR TITLE
Add lifetimes for `DBIterator` return types 

### PR DESCRIPTION
**Pull request by ngotchac**
Without them, the added simple test case doesn't compile.

### CODE REVIEW

**Comment by iSynaptic** [comment]
Restarting build since the failure seemed to be a transient issue.

**Comment by iSynaptic** [comment]
Closing and re-opening to trigger build...

**Comment by iSynaptic** [comment]
This code compiles without any changes (there was a transient build server issue that has resolved itself).  This adds lifetimes to `DBIterator`, which I believe is correct since an iterators life is tied to the life of the `DB`, but that means it's a breaking change. Better to get the lifetimes right now than want to change them after a `1.0` release.

@aleksuss @vitvakatu Thoughts?

**Comment by iSynaptic** [comment]
Worth noting I made the same change in my draft PR #268:

https://github.com/rust-rocksdb/rust-rocksdb/pull/268/files#diff-d1e45ae73f0ad58210abebd18b410da6R115

**Comment by nbdd0121** [comment]
Can we also get the get APIs sorted out properly as well, consider that this PR introduces a breaking change anyway? We should remove the existing `get` APIs and rename the `get_pinned` once to `get` (see #337). `get_pinned` is much faster than `get`, except that it returns `'self` instead `'static`.

**Comment by aleksuss** [comment]
@nbdd0121 Have you done benchmarks to measure that a `get_pinned` is really faster then `get` ?

**Comment by nbdd0121** [comment]
> @nbdd0121 Have you done benchmarks to measure that a `get_pinned` is really faster then `get` ?

Yes. It has very large performance advantage:
```
test get_large                 ... bench:     153,760 ns/iter (+/- 5,751)
test get_pinned_large          ... bench:       3,147 ns/iter (+/- 203)
test get_pinned_small          ... bench:         141 ns/iter (+/- 5)
test get_pinned_to_owned_large ... bench:       6,804 ns/iter (+/- 485)
test get_pinned_to_owned_small ... bench:         157 ns/iter (+/- 5)
test get_small                 ... bench:         156 ns/iter (+/- 9)
```

Small payload is 5 bytes, and large payload is the full lorem ipsum text repeated 100 times. "get_pinned_to_owned" uses "slice.as_ref().to_owned()" which converts `DBPinnableSlice` to `Vec<u8>`. Do you want me to create a PR which switchs `get` to use pinned APIs, and deprecate `get_pinned`?

**Pull request merged**
