### PR TITLE
Add support for range delete APIs

### PR DESCRIPTION
**Pull request by wqfish**
This change exposes the range delete C APIs added in https://github.com/facebook/rocksdb/pull/6259.

### CODE REVIEW

**Comment by ordian** [comment]
How is it different from https://docs.rs/rocksdb/0.13.0/rocksdb/struct.WriteBatch.html#method.delete_range_cf?

**Comment by aleksuss** [comment]
Obviously, that it could be done directly via `DB` rather than via `WriteBatch` ?

**Comment by ordian** [comment]
In terms of functionality, this PR provides a way pass `WriteOptions` to delete range function. Would be nice to document how a user is supposed use that, e.g. which options could be useful when deleting a range.

**Comment by wqfish** [comment]
> How is it different from https://docs.rs/rocksdb/0.13.0/rocksdb/struct.WriteBatch.html#method.delete_range_cf?

It's similar to other methods like `put` and `delete`:
1. They can be done directly on the DB if that's all the user needs
2. If the user wants to combine the operation with a few other ones and make an atomic write, they do it via `WriteBatch`.

> In terms of functionality, this PR provides a way pass `WriteOptions` to delete range function. Would be nice to document how a user is supposed use that, e.g. which options could be useful when deleting a range.

The write options aren't specific to the `delete_range` operation, it's the same for all the write operations. So the documentation probably should go to `WriteOptions`.

**Pull request merged**
